version: '3.7'
services:

  kwmbridge-app:
    image: tiredofit/kopano-kwmbridge:latest
    container_name: kwmbridge-app
    volumes:
      - ./logs/kwmbridge:/logs
      - ./config:/config
      - ./certs:/certs
      - ./assets/custom:/assets/custom
    environment:
      - TIMEZONE=America/Vancouver
      - CONTAINER_LOG_LEVEL=INFO
      - DEBUG_MODE=FALSE
      - LOG_LEVEL=INFO
    networks:
      - services
    restart: always

networks:
  services:
    external: true
